- hosts: localhost
  become: yes
  tasks:

  - name: Create mongo data folder
    file:
      path: /data/mongo/
      state: directory

  - name: Create mongo data folder
    file:
      path: /data/mongo_conf
      state: directory

  - name: Create network if it doesn't exist
    community.docker.docker_network:
      name: "{{ network }}"

  - name: Stop and remove mongodb container
    community.docker.docker_container:
      container_default_behavior: no_defaults
      name: mongodb
      image: mongo
      state: absent
      keep_volumes: true
      force_kill: true

  - name: Run mongo container
    community.docker.docker_container:
      container_default_behavior: no_defaults
      name: mongodb
      image: mongo
      state: started
      published_ports :
        - 0.0.0.0:2400:27017
      volumes:
        - /data/mongo:/data/db
      networks:
        - name: "{{ network }}"