- hosts: localhost
  become: yes
  tasks:

  - name: Delete default nginx config
    file:
      path: "/var/lib/docker/volumes/nginx_data/_data/conf.d/default.conf"
      state: absent

  - name: Delete old conf for the current domain on nginx
    file:
      path: "/var/lib/docker/volumes/nginx_data/_data/conf.d/{{ domain }}.conf"
      state: absent

  - name: Add config 
    ansible.builtin.blockinfile:
      path: "/var/lib/docker/volumes/nginx_data/_data/conf.d/{{ domain }}.conf"
      create: true
      mode: a+rwx
      block: |
        server {
          listen 443 ssl;
          listen [::]:443 ssl;
          server_name {{ domain }};

            # SSL certificate and key
            ssl_certificate /etc/nginx/conf.d/live/{{ domain }}/fullchain.pem;
            ssl_certificate_key /etc/nginx/conf.d/live/{{ domain }}/privkey.pem;

            # SSL configuration options
            ssl_protocols TLSv1.2 TLSv1.3;
            ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA;
            ssl_prefer_server_ciphers on;

            location / {
                proxy_pass http://{{docker_host}};
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
      state: present

  - name: Run nginx container
    community.docker.docker_container:
      container_default_behavior: no_defaults
      name: nginx
      state: started
      restart: true
